/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lycan.apptienda.vistas.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lycan.apptienda.entidades.Cliente;
import lycan.apptienda.entidades.Compra;
import lycan.apptienda.entidades.Cuenta;
import lycan.apptienda.entidades.Domicilio;
import lycan.apptienda.logica.Controladora;
import lycan.apptienda.persistencia.ControladoraPersistencia;

/**
 *
 * @author SANTIAGO
 */
public class VentanaRegistrarCompra extends javax.swing.JDialog {
    
    static int clicks;
    Cuenta cuenta;
    Cliente cliente;
    Date hoy = new Date();
    static String fecha_actual;
    public VentanaRegistrarCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Establecer color blanco de fondo
        this.getContentPane().setBackground(Color.WHITE);
        
        btRegistrar.setOpaque(true);
        
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        panelDatosCliente.setVisible(false);
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        lbValorCompra = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        lbIdCuenta = new javax.swing.JLabel();
        txtIdCuenta = new javax.swing.JTextField();
        lbPregunta = new javax.swing.JLabel();
        btConsultarCuenta = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        btLimpiarDatos = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelDatosCliente = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lbNumId = new javax.swing.JLabel();
        txtNumId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de clientes");
        setBackground(new java.awt.Color(255, 255, 255));

        PanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)), "Registrar una compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 1, 14))); // NOI18N

        lbValorCompra.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbValorCompra.setText("Valor de la compra");
        lbValorCompra.setToolTipText("");

        txtValorCompra.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtValorCompra.setToolTipText("");
        txtValorCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbIdCuenta.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbIdCuenta.setText("Ingrese el ID de la cuenta *");
        lbIdCuenta.setToolTipText("");

        txtIdCuenta.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtIdCuenta.setToolTipText("");
        txtIdCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        txtIdCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdCuentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdCuentaFocusLost(evt);
            }
        });

        lbPregunta.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        lbPregunta.setText("¿A qué cuenta se va asignar esta compra?");
        lbPregunta.setToolTipText("");

        btConsultarCuenta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btConsultarCuenta.setForeground(new java.awt.Color(0, 27, 110));
        btConsultarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/check-mark-black16px.png"))); // NOI18N
        btConsultarCuenta.setToolTipText("Buscar la cuenta");
        btConsultarCuenta.setBorder(null);
        btConsultarCuenta.setContentAreaFilled(false);
        btConsultarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsultarCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btConsultarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarCuentaActionPerformed(evt);
            }
        });

        lbMsg.setForeground(new java.awt.Color(126, 126, 126));

        btLimpiarDatos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btLimpiarDatos.setForeground(new java.awt.Color(0, 27, 110));
        btLimpiarDatos.setText("Limpiar campos");
        btLimpiarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btLimpiarDatos.setContentAreaFilled(false);
        btLimpiarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btLimpiarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseExited(evt);
            }
        });
        btLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarDatosActionPerformed(evt);
            }
        });

        btRegistrar.setBackground(new java.awt.Color(0, 27, 110));
        btRegistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrar.setText("Registrar");
        btRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.setEnabled(false);
        btRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegistrarMouseExited(evt);
            }
        });
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(txtIdCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbIdCuenta)
                            .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValorCompra)
                            .addComponent(lbPregunta))
                        .addGap(2, 2, 2)))
                .addGap(59, 73, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbValorCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbIdCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdCuenta)
                    .addComponent(btConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 110));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/store64px.png"))); // NOI18N
        jLabel1.setText("  TIENDA LYCAN ™");

        panelDatosCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)), "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 1, 14))); // NOI18N

        lbNombre.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbNombre.setText("Nombre");
        lbNombre.setToolTipText("");

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(126, 126, 126));
        txtNombre.setToolTipText("");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbTelefono.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbTelefono.setText("Telefono");
        lbTelefono.setToolTipText("");

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(126, 126, 126));
        txtTelefono.setToolTipText("");
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbNumId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbNumId.setText("Num. identificación del cliente");
        lbNumId.setToolTipText("");

        txtNumId.setEditable(false);
        txtNumId.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtNumId.setForeground(new java.awt.Color(126, 126, 126));
        txtNumId.setToolTipText("");
        txtNumId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNumId, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(lbNumId))
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNumId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/Salir24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(142, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        
        try {
            int valor_compra = Integer.parseInt(txtValorCompra.getText());
            
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");//Se crea un formato de fecha
            fecha_actual = formatoFecha.format(hoy); //Formatea el objeto de tipo Date a una cadena
            Date fecha_compra = formatoFecha.parse(fecha_actual);//Se convierte la fecha formateada como cadena en un objeto Date
            
            cuenta.setTotal_deuda(cuenta.getTotal_deuda() + valor_compra);
            
            Compra compra = new Compra(fecha_compra, valor_compra, cliente);
            compra.setCuenta(cuenta);
            
            
            Controladora control = new Controladora();
            control.insertCompra(compra);
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btConsultarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarCuentaActionPerformed
        try {
            int id_cuenta = Integer.parseInt(txtIdCuenta.getText());
            Controladora control = new Controladora();
            
            cuenta = control.buscarCuenta(id_cuenta);
            lbMsg.setText("Encontrada!");
            btRegistrar.setEnabled(true);
            
            cliente = cuenta.getCliente();
            
            String nombre = cliente.getPrimer_nombre() + " " + cliente.getPrimer_apellido();
            long telefono = cliente.getTelefono();
            int num_id = cliente.getIdentificacion();
            
            txtNombre.setText(nombre);
            txtTelefono.setText(String.valueOf(telefono));
            txtNumId.setText(String.valueOf(num_id));
            
            panelDatosCliente.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btConsultarCuentaActionPerformed

    private void btRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseClicked
        
        if (!btRegistrar.isEnabled()) clicks++;
        
        if (clicks >= 3) txtIdCuenta.requestFocus();
    }//GEN-LAST:event_btRegistrarMouseClicked
     
    private void txtIdCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCuentaFocusGained
        txtIdCuenta.setBorder(BorderFactory.createLineBorder(new Color(96, 128, 236)));
    }//GEN-LAST:event_txtIdCuentaFocusGained

    private void txtIdCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCuentaFocusLost
        txtIdCuenta.setBorder(BorderFactory.createLineBorder(new Color(209,209,209)));
    }//GEN-LAST:event_txtIdCuentaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarDatosActionPerformed

        txtValorCompra.setText("");
        txtNumId.setText("");
        txtIdCuenta.setText("");
        lbMsg.setText("");
    }//GEN-LAST:event_btLimpiarDatosActionPerformed

    private void btLimpiarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseEntered
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(new Color(209,209,209));
    }//GEN-LAST:event_btLimpiarDatosMouseEntered

    private void btLimpiarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseExited
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btLimpiarDatosMouseExited

    private void btRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseEntered
        btRegistrar.setBackground(Color.WHITE);
        btRegistrar.setForeground(new Color(0,27,110));
    }//GEN-LAST:event_btRegistrarMouseEntered

    private void btRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseExited
        btRegistrar.setBackground(new Color(0,27,110));
        btRegistrar.setForeground(Color.WHITE);
        //btRegistrar.setBorder(BorderFactory.createLineBorder(new Color(0,27,110)));
    }//GEN-LAST:event_btRegistrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        ControladoraPersistencia controla = new ControladoraPersistencia();
        /* Create and display the dialog */
        //ControladoraPersistencia conPer = new ControladoraPersistencia();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistrarCompra dialog = new VentanaRegistrarCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JButton btConsultarCuenta;
    private javax.swing.JButton btLimpiarDatos;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbIdCuenta;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumId;
    private javax.swing.JLabel lbPregunta;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbValorCompra;
    private javax.swing.JPanel panelDatosCliente;
    private javax.swing.JTextField txtIdCuenta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumId;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorCompra;
    // End of variables declaration//GEN-END:variables
}
