/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lycan.apptienda.vistas.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lycan.apptienda.entidades.Cliente;
import lycan.apptienda.entidades.Cuenta;
import lycan.apptienda.entidades.Domicilio;
import lycan.apptienda.logica.Controladora;
import lycan.apptienda.persistencia.ControladoraPersistencia;

/**
 *
 * @author SANTIAGO
 */
public class VentanaRegistrarCuenta extends javax.swing.JDialog {
    
    static int clicks;
    Cliente cliente;
    Date hoy = new Date();
    static String fecha_actual;
    public VentanaRegistrarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Establecer color blanco de fondo
        this.getContentPane().setBackground(Color.WHITE);
        
        btRegistrar.setOpaque(true);
        
        
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        fecha_actual = formatoFecha.format(hoy);
        txtFechaApertura.setText(fecha_actual);
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        lbFechaApertura = new javax.swing.JLabel();
        txtFechaApertura = new javax.swing.JTextField();
        lbFechaCancelacion = new javax.swing.JLabel();
        txtFechaCancelacion = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        lbTotalCancelado = new javax.swing.JLabel();
        txtTotalCancelado = new javax.swing.JTextField();
        lbIdentificacion = new javax.swing.JLabel();
        txtNumId = new javax.swing.JTextField();
        lbTotalDeuda = new javax.swing.JLabel();
        txtDeuda = new javax.swing.JTextField();
        lbPregunta = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        btConsultarCliente = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        btLimpiarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de clientes");
        setBackground(new java.awt.Color(255, 255, 255));

        PanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)), "Registrar datos de la cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 1, 14))); // NOI18N

        lbFechaApertura.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbFechaApertura.setText("Fecha de apertura");
        lbFechaApertura.setToolTipText("");

        txtFechaApertura.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtFechaApertura.setToolTipText("");
        txtFechaApertura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        txtFechaApertura.setEnabled(false);

        lbFechaCancelacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbFechaCancelacion.setText("Fecha de cancelación");
        lbFechaCancelacion.setToolTipText("");

        txtFechaCancelacion.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtFechaCancelacion.setToolTipText("");
        txtFechaCancelacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbEstado.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbEstado.setText("Estado");
        lbEstado.setToolTipText("");

        lbTotalCancelado.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbTotalCancelado.setText("Total cancelado");
        lbTotalCancelado.setToolTipText("");

        txtTotalCancelado.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTotalCancelado.setToolTipText("");
        txtTotalCancelado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbIdentificacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbIdentificacion.setText("Ingrese el num. de identificación");
        lbIdentificacion.setToolTipText("");

        txtNumId.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtNumId.setToolTipText("");
        txtNumId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        txtNumId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumIdFocusLost(evt);
            }
        });

        lbTotalDeuda.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbTotalDeuda.setText("Total deuda");
        lbTotalDeuda.setToolTipText("");

        txtDeuda.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtDeuda.setText("0");
        txtDeuda.setToolTipText("");
        txtDeuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbPregunta.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        lbPregunta.setText("¿A qué cliente va a pertenecer \nesta cuenta?");
        lbPregunta.setToolTipText("");

        jComboEstado.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva" }));
        jComboEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        btConsultarCliente.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btConsultarCliente.setForeground(new java.awt.Color(0, 27, 110));
        btConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/check-mark-black16px.png"))); // NOI18N
        btConsultarCliente.setBorder(null);
        btConsultarCliente.setContentAreaFilled(false);
        btConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsultarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarClienteActionPerformed(evt);
            }
        });

        btRegistrar.setBackground(new java.awt.Color(0, 27, 110));
        btRegistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrar.setText("Registrar");
        btRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.setEnabled(false);
        btRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistrarMouseClicked(evt);
            }
        });
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        lbMsg.setForeground(new java.awt.Color(126, 126, 126));

        btLimpiarDatos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btLimpiarDatos.setForeground(new java.awt.Color(0, 27, 110));
        btLimpiarDatos.setText("Limpiar campos");
        btLimpiarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btLimpiarDatos.setContentAreaFilled(false);
        btLimpiarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btLimpiarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseExited(evt);
            }
        });
        btLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaCancelacion, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lbFechaCancelacion)
                    .addComponent(txtDeuda, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lbTotalDeuda)
                    .addComponent(txtTotalCancelado, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lbTotalCancelado)
                    .addComponent(lbEstado)
                    .addComponent(lbFechaApertura)
                    .addComponent(txtFechaApertura, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(18, 59, Short.MAX_VALUE)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPregunta)
                    .addComponent(lbIdentificacion)
                    .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelDatosLayout.createSequentialGroup()
                            .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosLayout.createSequentialGroup()
                            .addComponent(txtNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(82, 82, 82))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbFechaApertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPregunta))
                .addGap(24, 24, 24)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(lbFechaCancelacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaCancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(lbIdentificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumId)
                            .addComponent(btConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEstado)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbTotalCancelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbTotalDeuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 110));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/store64px.png"))); // NOI18N
        jLabel1.setText("  TIENDA LYCAN ™");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/Salir24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        
        String estado = (String) jComboEstado.getSelectedItem();
        
        try {
            DateFormat formato = DateFormat.getDateInstance(DateFormat.SHORT);
            Date fecha_apertura = formato.parse(fecha_actual);
            Date fecha_cancelacion = formato.parse(txtFechaCancelacion.getText());
            
            int total_cancelado = Integer.parseInt(txtTotalCancelado.getText());
            int total_deuda = Integer.parseInt(txtDeuda.getText());
            
            Cuenta cuenta = new Cuenta(total_deuda, fecha_apertura, fecha_cancelacion, estado, total_cancelado);
            cuenta.setCliente(cliente);
            
            Controladora control = new Controladora();
            control.insertCuenta(cuenta);
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarClienteActionPerformed
        try {
            int identi = Integer.parseInt(txtNumId.getText());
            Controladora control = new Controladora();
            
            cliente = control.buscarCliente(identi);
            lbMsg.setText("Encontrado!");
            btRegistrar.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btConsultarClienteActionPerformed

    private void btRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseClicked
        
        if (!btRegistrar.isEnabled()) clicks++;
        
        if (clicks >= 3) txtNumId.requestFocus();
    }//GEN-LAST:event_btRegistrarMouseClicked
     
    private void txtNumIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumIdFocusGained
        txtNumId.setBorder(BorderFactory.createLineBorder(new Color(96, 128, 236)));
    }//GEN-LAST:event_txtNumIdFocusGained

    private void txtNumIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumIdFocusLost
        txtNumId.setBorder(BorderFactory.createLineBorder(new Color(209,209,209)));
    }//GEN-LAST:event_txtNumIdFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarDatosActionPerformed

        txtFechaCancelacion.setText("");
        txtTotalCancelado.setText("");
        txtDeuda.setText("");
        txtNumId.setText("");
        lbMsg.setText("");
    }//GEN-LAST:event_btLimpiarDatosActionPerformed

    private void btLimpiarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseEntered
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(new Color(209,209,209));
    }//GEN-LAST:event_btLimpiarDatosMouseEntered

    private void btLimpiarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseExited
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btLimpiarDatosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        //ControladoraPersistencia conPer = new ControladoraPersistencia();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistrarCuenta dialog = new VentanaRegistrarCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JButton btConsultarCliente;
    private javax.swing.JButton btLimpiarDatos;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFechaApertura;
    private javax.swing.JLabel lbFechaCancelacion;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbPregunta;
    private javax.swing.JLabel lbTotalCancelado;
    private javax.swing.JLabel lbTotalDeuda;
    private javax.swing.JTextField txtDeuda;
    private javax.swing.JTextField txtFechaApertura;
    private javax.swing.JTextField txtFechaCancelacion;
    private javax.swing.JTextField txtNumId;
    private javax.swing.JTextField txtTotalCancelado;
    // End of variables declaration//GEN-END:variables
}
