/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lycan.apptienda.vistas.gui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lycan.apptienda.entidades.Usuario;
import lycan.apptienda.logica.Controladora;
import lycan.apptienda.persistencia.ControladoraPersistencia;

/**
 *
 * @author SANTIAGO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static String nombre;
    
    public VentanaPrincipal() {
        initComponents();
        
        //Establecer color blanco de fondo
        this.getContentPane().setBackground(new Color(234, 234, 234));
        btIngresar.setOpaque(true);
        txtPass.setEchoChar('\u2022');
        
        //Maximizar la ventana
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.pack();
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
    }

    public String getNombre(){
        return nombre;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCabecera = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbSubCabecera = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btIngresar = new javax.swing.JButton();
        lbPass = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        TogglebtMostrarPass = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 27, 110));

        lbCabecera.setBackground(new java.awt.Color(0, 27, 110));
        lbCabecera.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        lbCabecera.setForeground(new java.awt.Color(255, 255, 255));
        lbCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCabecera.setText("¡BIENVENIDO!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 27, 110));

        lbSubCabecera.setBackground(new java.awt.Color(0, 27, 110));
        lbSubCabecera.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lbSubCabecera.setForeground(new java.awt.Color(255, 255, 255));
        lbSubCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubCabecera.setText("Iniciar sesión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSubCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lbSubCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        txtId.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        txtId.setToolTipText("");
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 234)));

        txtPass.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 234)));

        btIngresar.setBackground(new java.awt.Color(0, 27, 110));
        btIngresar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        btIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btIngresar.setText("INGRESAR");
        btIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 232, 255)));
        btIngresar.setContentAreaFilled(false);
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });

        lbPass.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbPass.setText("Contraseña");

        lbId.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbId.setText("Identificación");
        lbId.setToolTipText("");

        TogglebtMostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/eye_black_24px.png"))); // NOI18N
        TogglebtMostrarPass.setContentAreaFilled(false);
        TogglebtMostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogglebtMostrarPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbId)
                    .addComponent(lbPass)
                    .addComponent(txtId)
                    .addComponent(btIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TogglebtMostrarPass)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TogglebtMostrarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TogglebtMostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogglebtMostrarPassActionPerformed
        ImageIcon icono;
        if (TogglebtMostrarPass.isSelected()) {
            //Muestra la contraseña - el parámetro 0 hace que el texto del campo sea visible
            txtPass.setEchoChar((char) 0);
            icono = new ImageIcon("C:\\Users\\SANTIAGO\\Documents\\NetBeansProjects\\ProyectoTienda\\Iconos\\hide_black_24px.png");
            TogglebtMostrarPass.setIcon(icono);
        } else {
            //Oculta la contraseña
            txtPass.setEchoChar('\u2022');
            icono = new ImageIcon("C:\\Users\\SANTIAGO\\Documents\\NetBeansProjects\\ProyectoTienda\\Iconos\\eye_black_24px.png");
            TogglebtMostrarPass.setIcon(icono);
        }
    }//GEN-LAST:event_TogglebtMostrarPassActionPerformed

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed

        try {

            boolean autorizacion;
            int id = Integer.parseInt(txtId.getText());
            String pass = String.valueOf(txtPass.getPassword());
            
            try{
                
                autorizacion = Usuario.iniciarSesión(id, pass);
                if (autorizacion == true){
                    
                    Controladora control = new Controladora();
                    Usuario user = control.buscarUsuario(id);
                    nombre = user.getPrimer_nombre() + " " + user.getPrimer_apellido();
                    
                    VentanaOperaciones frm = new VentanaOperaciones();
                    frm.setVisible(true);
                    this.dispose();
                }
                else JOptionPane.showMessageDialog(this, "No se pudo iniciar la sesión");
            }catch(Exception ex){
                
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //ControladoraPersistencia control = new ControladoraPersistencia();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TogglebtMostrarPass;
    private javax.swing.JButton btIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCabecera;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbSubCabecera;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
