/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lycan.apptienda.vistas.gui;

import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lycan.apptienda.entidades.Cliente;
import lycan.apptienda.entidades.Domicilio;
import lycan.apptienda.logica.Controladora;

/**
 *
 * @author SANTIAGO
 */
public class VentanaRegistrarCliente extends javax.swing.JDialog {

    Cliente cliente;
    Domicilio domi;
    int clicks = 0;
    
    public VentanaRegistrarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Establecer color blanco de fondo
        this.getContentPane().setBackground(Color.WHITE);
        
        btRegistrar.setOpaque(true);
        
        //Centrar la ventana
        this.setLocationRelativeTo(null);
        
        
    }
    
    private void habilitarComponentes(JPanel panel){
        
        Component[] componentes = panel.getComponents();
        
        for (Component componente : componentes){
            componente.setEnabled(true);
        }
    }
    
    public void validarCorreo(String correo)throws Exception{
        if (!correo.contains("@") || !correo.endsWith(".com")) {
            throw new Exception("El correo ingresado no es valido");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        lbSecondNombre = new javax.swing.JLabel();
        txtSecondNombre = new javax.swing.JTextField();
        lbPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lbSecondApellido = new javax.swing.JLabel();
        txtSecondApellido = new javax.swing.JTextField();
        lbIdentificacion = new javax.swing.JLabel();
        txtNumId = new javax.swing.JTextField();
        lbCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        PanelDireccion = new javax.swing.JPanel();
        lbBarrio = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        lbCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btRegistrar = new javax.swing.JButton();
        btRegistrarDatos = new javax.swing.JButton();
        lbMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btLimpiarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de clientes");
        setBackground(new java.awt.Color(255, 255, 255));

        PanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)), "Registrar datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 1, 14))); // NOI18N

        lbNombre.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbNombre.setText("Primer nombre *");
        lbNombre.setToolTipText("");

        txtPrimerNombre.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtPrimerNombre.setToolTipText("");
        txtPrimerNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbSecondNombre.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbSecondNombre.setText("Segundo nombre");
        lbSecondNombre.setToolTipText("");

        txtSecondNombre.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtSecondNombre.setToolTipText("");
        txtSecondNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbPrimerApellido.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbPrimerApellido.setText("Primer apellido *");
        lbPrimerApellido.setToolTipText("");

        txtPrimerApellido.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtPrimerApellido.setToolTipText("");
        txtPrimerApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbSecondApellido.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbSecondApellido.setText("Segundo apellido *");
        lbSecondApellido.setToolTipText("");

        txtSecondApellido.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtSecondApellido.setToolTipText("");
        txtSecondApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbIdentificacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbIdentificacion.setText("Número de identificación *");
        lbIdentificacion.setToolTipText("");

        txtNumId.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtNumId.setToolTipText("");
        txtNumId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbCorreo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbCorreo.setText("Email");
        lbCorreo.setToolTipText("");

        txtCorreo.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtCorreo.setToolTipText("");
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lblTelefono.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lblTelefono.setText("Teléfono *");
        lblTelefono.setToolTipText("");

        txtTelefono.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtTelefono.setToolTipText("");
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSecondApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSecondApellido)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrimerApellido)
                    .addComponent(txtSecondNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSecondNombre)
                    .addComponent(lbNombre)
                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentificacion)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCorreo)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(72, 72, 72))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(lbNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(lbIdentificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(lbSecondNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSecondNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(lbCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(lbPrimerApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(lbSecondApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSecondApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDireccion.setBackground(new java.awt.Color(255, 255, 255));
        PanelDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Variable", 1, 14))); // NOI18N

        lbBarrio.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbBarrio.setText("Barrio *");
        lbBarrio.setToolTipText("");

        txtBarrio.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtBarrio.setToolTipText("");
        txtBarrio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbCalle.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbCalle.setText("Calle *");
        lbCalle.setToolTipText("");

        txtCalle.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtCalle.setToolTipText("");
        txtCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        lbDireccion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        lbDireccion.setText("Dirección *");
        lbDireccion.setToolTipText("");

        txtDireccion.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        txtDireccion.setToolTipText("");
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));

        javax.swing.GroupLayout PanelDireccionLayout = new javax.swing.GroupLayout(PanelDireccion);
        PanelDireccion.setLayout(PanelDireccionLayout);
        PanelDireccionLayout.setHorizontalGroup(
            PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDireccionLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDireccion)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCalle)
                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBarrio))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        PanelDireccionLayout.setVerticalGroup(
            PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDireccionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbBarrio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbCalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 110));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/store64px.png"))); // NOI18N
        jLabel1.setText("  TIENDA LYCAN ™");

        btRegistrar.setBackground(new java.awt.Color(0, 27, 110));
        btRegistrar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrar.setText("Registrar");
        btRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btRegistrar.setContentAreaFilled(false);
        btRegistrar.setEnabled(false);
        btRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistrarMouseClicked(evt);
            }
        });
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        btRegistrarDatos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btRegistrarDatos.setForeground(new java.awt.Color(0, 27, 110));
        btRegistrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/check16px.png"))); // NOI18N
        btRegistrarDatos.setText("Guardar los datos");
        btRegistrarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btRegistrarDatos.setContentAreaFilled(false);
        btRegistrarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btRegistrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegistrarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegistrarDatosMouseExited(evt);
            }
        });
        btRegistrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarDatosActionPerformed(evt);
            }
        });

        lbMensaje.setForeground(new java.awt.Color(126, 126, 126));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lycan/apptienda/vistas/gui/iconos/Salir24px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btLimpiarDatos.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btLimpiarDatos.setForeground(new java.awt.Color(0, 27, 110));
        btLimpiarDatos.setText("Limpiar campos");
        btLimpiarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 209, 209)));
        btLimpiarDatos.setContentAreaFilled(false);
        btLimpiarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btLimpiarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimpiarDatosMouseExited(evt);
            }
        });
        btLimpiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btRegistrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRegistrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarDatosActionPerformed
        
        try{
            /*DATOS PERSONALES DEL CLIENTE*/
            String primer_nombre = txtPrimerNombre.getText();
            boolean esOblogatorioPrimerNombre = true;
        
            String segundo_nombre = txtSecondNombre.getText();
        
            String primer_apellido = txtPrimerApellido.getText();
            boolean esOblogatorioPrimerApellido = true;
        
            String segundo_apellido = txtSecondApellido.getText();
            boolean esOblogatorioSegundoApellido = true;
        
            String correo = txtCorreo.getText();
        
            int num_id = Integer.parseInt(txtNumId.getText());
            boolean esOblogatorioIdentificacion = true;
        
            long telefono = Long.parseLong(txtTelefono.getText());
            boolean esOblogatorioTelefono = true;
            
            /*DIRECCIÓN DEL CLIENTE*/
            String barrio = txtBarrio.getText();
            boolean esOblogatorioBarrio = true;
            
            String calle = txtCalle.getText();
            boolean esOblogatorioCalle = true;
            
            String direccion = txtDireccion.getText();
            boolean esOblogatorioDireccion = true;
            
            try{
            
                if(esOblogatorioPrimerNombre && primer_nombre.isEmpty()) throw new Exception ("El campo Primer nombre es obligatorio");
                if(esOblogatorioPrimerApellido && primer_apellido.isEmpty()) throw new Exception ("El campo Primer apellido es obligatorio");
                if(esOblogatorioSegundoApellido && segundo_apellido.isEmpty()) throw new Exception ("El campo Segundo apellido es obligatorio");
                if(esOblogatorioIdentificacion && txtNumId.getText().equals("")) throw new Exception ("El campo Identificación es obligatorio");
                if(esOblogatorioTelefono && txtTelefono.getText().equals("")) throw new Exception ("El campo Teléfono es obligatorio");
                if(esOblogatorioBarrio && txtBarrio.getText().equals("")) throw new Exception ("El campo Barrio es obligatorio");
                if(esOblogatorioCalle && txtCalle.getText().equals("")) throw new Exception ("El campo Calle es obligatorio");
                if(esOblogatorioDireccion && txtDireccion.getText().equals("")) throw new Exception ("El campo Dirección es obligatorio");
                if (!correo.isEmpty()) validarCorreo(correo);
                
                cliente = new Cliente (telefono, correo, num_id, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido);
                domi = new Domicilio(barrio, calle, direccion);
                cliente.setDomicilio(domi);
                JOptionPane.showMessageDialog(null, "Los datos se han guardado");
                lbMensaje.setText("");
                btRegistrar.setEnabled(true);
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                
        
    }//GEN-LAST:event_btRegistrarDatosActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        
        try {
            Controladora control = new Controladora();
            control.insertClient(cliente);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseClicked
        
        clicks++;
        if(clicks >= 3) lbMensaje.setText("Primero guarde los datos por favor");
    }//GEN-LAST:event_btRegistrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btLimpiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarDatosActionPerformed
        
        txtPrimerNombre.setText("");
        txtSecondNombre.setText("");
        txtPrimerApellido.setText("");
        txtSecondApellido.setText("");
        txtNumId.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtBarrio.setText("");
        txtCalle.setText("");
        txtDireccion.setText("");
    }//GEN-LAST:event_btLimpiarDatosActionPerformed

    private void btRegistrarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarDatosMouseEntered
        btRegistrarDatos.setOpaque(true);
        btRegistrarDatos.setBackground(new Color(209,209,209));
    }//GEN-LAST:event_btRegistrarDatosMouseEntered

    private void btRegistrarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarDatosMouseExited
        btRegistrarDatos.setOpaque(true);
        btRegistrarDatos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btRegistrarDatosMouseExited

    private void btLimpiarDatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseEntered
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(new Color(209,209,209));
    }//GEN-LAST:event_btLimpiarDatosMouseEntered

    private void btLimpiarDatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimpiarDatosMouseExited
        btLimpiarDatos.setOpaque(true);
        btLimpiarDatos.setBackground(Color.WHITE);
    }//GEN-LAST:event_btLimpiarDatosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaRegistrarCliente dialog = new VentanaRegistrarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelDireccion;
    private javax.swing.JButton btLimpiarDatos;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btRegistrarDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBarrio;
    private javax.swing.JLabel lbCalle;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrimerApellido;
    private javax.swing.JLabel lbSecondApellido;
    private javax.swing.JLabel lbSecondNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNumId;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSecondApellido;
    private javax.swing.JTextField txtSecondNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
